[workspace]
members = ["fuzz"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[package]
name = "rustc_apfloat"
license = "Apache-2.0 WITH LLVM-exception"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags = "1.3.2"
smallvec = "1.10"
