[package]
name = "rustc_apfloat-fuzz"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
afl = "0.12.16"
clap = { version = "4.1.13", features = ["derive"] }
num-traits = "0.2.15"
rustc_apfloat = { path = ".." }
